name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Unit Tests
        run: mvn verify
        
  Coverage:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Coverage
        uses: cicirello/jacoco-badge-generator@v2
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          on-missing-report: fail
          fail-if-coverage-less-than: 75
          fail-if-branches-less-than: 75
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false
