name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        
  Maven-Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: jacoco-reports
          path: target/site/jacoco
          
      - name: Check Coverage
        uses: cicirello/jacoco-badge-generator@v2
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          on-missing-report: fail
          fail-if-coverage-less-than: 75
          fail-if-branches-less-than: 75
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false
          
  JUnit-Test:
    needs: Build
    runs-on: ubuntu-latestname
    steps:
      - name: Download junit console starter
        run: curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0-M1/junit-platform-console-standalone-1.8.0-M1.jar
      - name: Compile and Run JUnit Tests
        run: |
          mkdir compiled
          find src -name "*.java" > sources.txt
          javac -d compiled -cp junit-platform-console-standalone-1.8.0-M1.jar @sources.txt
          java -jar junit-platform-console-standalone-1.8.0-M1.jar --class-path compiled --scan-class-path
